In [ ]:
%pip install --quiet "evadb[document]"
import evadb
cursor = evadb.connect().cursor()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 550.5/550.5 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.6/137.6 kB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.6/111.6 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 kB 9.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 56.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 46.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 46.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 8.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 54.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 80.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 10.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 45.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 24.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 95.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 83.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 14.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 26.8 MB/s eta 0:00:00
  Building wheel for bs4 (setup.py) ... done
  Building wheel for sentence-transformers (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires tiktoken, which is not installed.

Downloading: "http://ml.cs.tsinghua.edu.cn/~chenxi/pytorch-models/mnist-b07bb66b.pth" to /root/.cache/torch/hub/checkpoints/mnist-b07bb66b.pth
100%|██████████| 1.03M/1.03M [00:01<00:00, 639kB/s]
Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /root/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth

In [19]:

import warnings
warnings.filterwarnings("ignore")
import os
import openai
os.environ['OPENAI_KEY'] = 'sk-.....'
open_ai_key = os.environ.get('OPENAI_KEY')
openai.api_key = open_ai_key
!apt install postgresql
!service postgresql start
!sudo -u postgres psql -c "CREATE USER eva WITH SUPERUSER PASSWORD 'password'"
!sudo -u postgres psql -c "CREATE DATABASE evadb"
params = {
    "user": "eva",
    "password": "password",
    "host": "localhost",
    "port": "5432",
    "database": "evadb",
}
query = f"CREATE DATABASE postgres_data WITH ENGINE = 'postgres', PARAMETERS = {params};"
cursor.query(query).df()

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
postgresql is already the newest version (14+238).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
 * Starting PostgreSQL 14 database server
   ...done.
ERROR:  role "eva" already exists
ERROR:  database "evadb" already exists

10-27-2023 04:15:44 ERROR [plan_executor:plan_executor.py:execute_plan:0179] postgres_data already exists.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/evadb/executor/plan_executor.py", line 175, in execute_plan
    yield from output
  File "/usr/local/lib/python3.10/dist-packages/evadb/executor/create_database_executor.py", line 42, in exec
    raise ExecutorError(f"{self.node.database_name} already exists.")
evadb.executor.executor_utils.ExecutorError: postgres_data already exists.
ERROR:evadb.utils.logging_manager:postgres_data already exists.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/evadb/executor/plan_executor.py", line 175, in execute_plan
    yield from output
  File "/usr/local/lib/python3.10/dist-packages/evadb/executor/create_database_executor.py", line 42, in exec
    raise ExecutorError(f"{self.node.database_name} already exists.")
evadb.executor.executor_utils.ExecutorError: postgres_data already exists.

ExecutorError: ignored

In [21]:
createTable = f"""
CREATE TABLE IF NOT EXISTS PLAYERDATA(
    sofifa_id INTEGER PRIMARY KEY,
    short_name TEXT,
    long_name TEXT,
    player_positions TEXT,
    overall INTEGER,
    potential INTEGER,
    wage_eur FLOAT(64,64),
    value_eur FLOAT(64,64),
    age INTEGER
);
"""
cursor.query(createTable).execute()

10-27-2023 04:16:21 WARNING[executor_utils:executor_utils.py:handle_if_not_exists:0094] Table: PLAYERDATA already exists
WARNING:evadb.utils.logging_manager:Table: PLAYERDATA already exists

In [40]:
loadData = f""" LOAD CSV 'out.csv' INTO PLAYERDATA;"""
cursor.query(loadData).execute()

In [41]:
cursor.query("""select * from PLAYERDATA""").df()

,_row_id,sofifa_id,short_name,long_name,player_positions,overall,potential,wage_eur,value_eur,age
0,1,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,320000.0,78000000.0,34
1,2,188545,R. Lewandowski,Robert Lewandowski,ST,92,92,270000.0,119500000.0,32
2,3,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,270000.0,45000000.0,36
3,4,190871,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,270000.0,129000000.0,29
4,5,192985,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,350000.0,125500000.0,30
...,...,...,...,...,...,...,...,...,...,...
95,96,212831,Alisson,Alisson Ramsés Becker,GK,89,90,190000.0,82000000.0,28
96,97,230621,G. Donnarumma,Gianluigi Donnarumma,GK,89,93,110000.0,119500000.0,22
97,98,155862,Sergio Ramos,Sergio Ramos García,CB,88,88,115000.0,24000000.0,35
98,99,176580,L. Suárez,Luis Alberto Suárez Díaz,ST,88,88,135000.0,44500000.0,34
99,100,182521,T. Kroos,Toni Kroos,CM,88,88,310000.0,75000000.0,31

In [42]:
def ChatWithPandas(message, tableName):
    try:
        # Interact with the chat model
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",  # you can define other models as well.
            messages=[
                {"role": "system", "content": f"""You are a helpful assistant that converts English sentence to SQL in postgresql.
                First we need to know the schema of {tableName} and then run the
                SELECT column_name, data_type
                FROM information_schema.columns
                WHERE table_name = '{tableName}';"""},
                {"role": "user", "content": message},
            ],
        )

        sql_query = response.choices[0].message['content']

    except Exception as e:
        print(f"An error occurred: {str(e)}")
        return None

    return sql_query

In [63]:
result_df = ChatWithPandas('output the sum of the age in the dataset', 'PLAYERDATA')
chat_query1 = f"""{result_df}"""
cursor.query(chat_query1).df()

    age
0  2964

In [61]:
result_df2 = ChatWithPandas('output the top wage_eur in the dataset', 'PLAYERDATA')
chat_query2 = f"""{result_df2}"""
cursor.query(chat_query2).df()

SELECT MAX(wage_eur) FROM PLAYERDATA;

   wage_eur
0  350000.0